### ISSUE TITLE
library name clash

### ISSUE THREAD

**Issue by vushu** [deepcake/echo#1]
As the title says, I had a slight issue, since I won't be able to use both libraries on the same time

https://lib.haxe.org/p/echo/

are you are planning to add to haxelib? :)

**Comment by deepcake** [comment]
Yeah, I saw that library a few days ago. Most likely, I will rename my lib to `echos` to fix the name conflict.

As for haxelib, I do not plan to add anytime soon. My lib does not yet look complete.

Thanks!
