### ISSUE TITLE
Can't iterate over all entities

### ISSUE THREAD

**Issue by player-03** [deepcake/echo#3]
If you define an update function that takes an `Entity` and no components, compilation will fail with the message "`SystemMacro.hx:66: characters 48-50 : Unknown identifier : id`." I believe this is caused by [the `if` block starting at line 203](https://github.com/deepcake/echo/blob/master/src/echos/macro/SystemMacro.hx#L203-L208), which returns a different macro when no components are needed.

I tested with and without a `Float` argument, and the result was the same. And just in case it matters, I tested in Haxe 3.

For me this isn't a high-priority issue; I can't think of any real-world reason to iterate over every single entity this way. I only came across this because I was trying to write a simple test case for something else. (Since I only added a single entity to the workflow, I didn't think I needed filters.)

**Comment by deepcake** [comment]
Well yeah, you are totally correct at all points. 
It's designed with presupposition that "no reason to iterate over every single entity this way".
But i think, i should make more informative error message for that case. Or just make it possible to iterate ids only.
Thanks!
